---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: wordpressinstances.wordpress.samples.stacks.crossplane.io
spec:
  preserveUnknownFields: true
  group: wordpress.samples.stacks.crossplane.io
  names:
    kind: WordpressInstance
    listKind: WordpressInstanceList
    plural: wordpressinstances
    singular: wordpressinstance
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WordpressInstance is the Schema for the wordpressinstances API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WordpressInstanceSpec defines the desired state of WordpressInstance
          properties:
            image:
              description: Image will be used as image of the container that Wordpress
                runs in. If not specified, the default will be used.
              type: string
            provisionPolicy:
              description: ProvisionPolicy indicates whether Wordpress should be deployed
                to an existing Kubernetes cluster or to provision a new cluster.
              enum:
              - ProvisionNewCluster
              - UseExistingTarget
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
