
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - compute.crossplane.io
  resources:
  - kubernetesclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.crossplane.io
  resources:
  - mysqlinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wordpress.samples.stacks.crossplane.io
  resources:
  - wordpressinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wordpress.samples.stacks.crossplane.io
  resources:
  - wordpressinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workload.crossplane.io
  resources:
  - kubernetesapplication
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
