{{ if ne (.Values.provisionPolicy | default "ProvisionNewCluster") "UseExistingTarget" }}
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: {{ .Release.Name }}-cluster
  labels:
    app: {{ .Release.Name }}
spec:
  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-cluster
{{ end }}

