# Human readable title of application.
title: Sample Wordpress Extension

# Markdown description of this entry
description: |
 Markdown describing this sample Crossplane extension project.

# Version of project (optional)
# If omitted the version will be filled with the docker tag
# If set it must match the docker tag
version: 0.0.1

# Maintainer names and emails.
maintainers:
- name: Daniel Suskin
  email: daniel@upbound.io

# Owner names and emails.
owners:
- name: Daniel Suskin
  email: daniel@upbound.io

# Human readable company name.
company: Upbound

# Keywords that describe this application and help search indexing
keywords:
- "samples"
- "examples"
- "tutorials"
- "wordpress"

# Links to more information about the application (about page, source code, etc.)
links:
- description: Website
  url: "https://upbound.io"
- description: Source Code
  url: "https://github.com/crossplaneio/sample-wordpress-extension"

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
