# Human readable title of application.
title: Sample Wordpress Stack

overviewShort: Cloud portable Wordpress deployments behind managed Kubernetes and SQL services are demonstrated in this Crossplane Stack.
overview: |-
 This Wordpress stack uses a simple controller that uses Crossplane to orchestrate managed SQL services and managed Kubernetes clusters which are then used to run a Wordpress deployment.

 A simple Custom Resource Definition (CRD) is provided allowing for instances of this Crossplane managed Wordpress Stack to be provisioned with a few lines of yaml.

 The Sample Wordpress Stack is intended for demonstration purposes and should not be used to deploy production instances of Wordpress.

# Markdown description of this entry
readme: |-
 ### Create wordpresses

 Before wordpresses will provision, the Crossplane control cluster must
 be configured to connect to a provider (e.g. GCP, Azure, AWS).

 Once a provider is configured, starting the process of creating a
 Wordpress Stack instance is easy.

 ```shell
 cat <<EOF | kubectl apply -f -
 apiVersion: wordpress.samples.stacks.crossplane.io/v1alpha1
 kind: WordpressInstance
 metadata:
   name: wordpressinstance-sample
 EOF
 ```

 The stack (and Crossplane) will take care of the rest.

# Maintainer names and emails.
maintainers:
- name: Daniel Suskin
  email: daniel@upbound.io

# Owner names and emails.
owners:
- name: Daniel Suskin
  email: daniel@upbound.io

# Human readable company name.
company: Upbound

# Type of package: Provider, Stack, or Application
packageType: Application

# Keywords that describe this application and help search indexing
keywords:
- "samples"
- "examples"
- "tutorials"
- "wordpress"

# Links to more information about the application (about page, source code, etc.)
website: "https://upbound.io"
source: "https://github.com/crossplane/sample-stack-wordpress"

# RBAC Roles will be generated permitting this stack to use all verbs on all
# resources in the groups listed below.
permissionScope: Namespaced
dependsOn:
- crd: "kubernetesclusters.compute.crossplane.io/v1alpha1"
- crd: "mysqlinstances.database.crossplane.io/v1alpha1"
- crd: "kubernetesapplications.workload.crossplane.io/v1alpha1"
- crd: "kubernetesapplicationresources.workload.crossplane.io/v1alpha1"

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
