rules:
- apiGroups:
  - wordpress.samples.stacks.crossplane.io
  resources:
  - wordpressinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wordpress.samples.stacks.crossplane.io
  resources:
  - wordpressinstances/status
  verbs:
  - get
  - patch
  - update
