apiVersion: apps/v1
kind: Deployment
metadata:
  name: "crossplane-sample-stack-wordpress"
  labels:
    core.crossplane.io/name: "crossplane-sample-stack-wordpress"
spec:
  selector:
    matchLabels:
      core.crossplane.io/name: "crossplane-sample-stack-wordpress"
  replicas: 1
  template:
    metadata:
      name: "crossplane-sample-stack-wordpress-controller"
      labels:
        core.crossplane.io/name: "crossplane-sample-stack-wordpress"
    spec:
      containers:
      - name: "crossplane-sample-stack-wordpress-controller"
        image: "crossplane/sample-stack-wordpress"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
